[build]
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile.collector"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
